---
components: 
  schemas: 
    Alert:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/Alert'
    NaturalDisasterAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/NaturalDisasterAlertCategories'
    HealthAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/HealthAlertCategories'
    SecurityAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/SecurityAlertCategories'
    TrafficAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/TrafficAlertCategories'
    EnvironmentAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/EnvironmentAlertCategories'
    AgriculturalAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Alert/alert/schema.yaml#/AgriculturalAlertCategories'
    WeatherAlertCategories:
      $ref: 'https://smart-data-models.github.io/dataModel.Weather/weather-schema.yaml#/WeatherAlertCategories'


info: 
  description: |
    This entity models an alert and could be used to send alerts related
    to traffic jam, accidents, weather conditions, high level of pollutants and so on. The purpose
    of the model is to support the generation of notifications for a user or trigger other actions,
    based on such alerts.

    An alert is generated by a specific situation. The main features of an alert is that it is not
    predictable and it is not a recurrent data. That means that an alert could be an accident or a
    high level of pollutants measure, additionally it could be the fall down of a patient or a car driving in the opposite direction.
    Some examples of context data are: type of alert (traffic, weather, security, and pollution, etc.), severity, location and so on.
  title: Alert
  version: "1.0.0"
openapi: "3.0.0"
  
# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Alert
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Alert/master/alert/example-1.json"
                normalized: 
                    summary: "Normalized NGSI-LD"
                    value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Alert/master/alert/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
